"""
Sanitazation of the CSV file generated by the evaluation, sometimes there are comas where there should not be ones    

Usage:
Change the path to the CSV file and run the script ;)

TODO: Add argument parsing for running the script from the terminal
"""

import os 
import json
import csv

import numpy as np

if __name__ == "__main__":
    csv_path = "/home/testbed/Projects/bop_toolkit/CNCpicking/results/foundationposepartial_CNCpicking-test.csv"
    with open(csv_path, "r") as f:
        reader = csv.reader(f)
        data = list(reader)

    new_data = []
    for e, row in enumerate(data):
        if e == 0: # header
            new_data.append(row)
            continue
        scene_id, im_id, obj_id, score, Rmx, t, time = row

        print(scene_id, im_id, obj_id, score, Rmx, t, time)
        # print(type(scene_id), type(im_id), type(obj_id), type(score), type(R), type(t), type(time))
        
        scene_id = int(scene_id)
        R = str(R).replace(",", "")
        t = str(t).replace(",", "")

        n_d = [scene_id, im_id, obj_id, score, Rmx, t, -1]
        new_data.append(n_d)

    with open(csv_path, "w") as f:
        print(f"Writing to {csv_path}")
        writer = csv.writer(f)
        writer.writerows(new_data)